/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_km_chat_custom_AESMessageMapper */

#ifndef _Included_com_km_chat_custom_AESMessageMapper
#define _Included_com_km_chat_custom_AESMessageMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_km_chat_custom_AESMessageMapper
 * Method:    encode
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_km_chat_custom_AESMessageMapper_encode
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_km_chat_custom_AESMessageMapper
 * Method:    decode
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_km_chat_custom_AESMessageMapper_decode
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
